### ISSUE TITLE
How exactly do you use it?

### ISSUE THREAD

**Issue by KyleChongHengKai** [0CottonBuds/Osu-Most-Played-Beatmap-Downloader#1]
![=(](https://github.com/0CottonBuds/Osu-Most-Played-Beatmap-Downloader/assets/148317693/736c58be-b4e4-4fe2-93e7-fea597296659)

**Comment by KyleChongHengKai** [comment]
where to change the name

**Comment by KyleChongHengKai** [comment]
why is it failing

**Comment by 0CottonBuds** [comment]
The repo was a mess before. Now when you run main.py you just need to answer the prompts for it to run.
